# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.ssh.private_key_path = '~/.ssh/id_rsa'
  config.vm.box = 'digital_ocean'
  config.vm.provider :digital_ocean do |provider|
    provider.client_id = ENV['DO_CLIENT_ID']
    provider.api_key = ENV['DO_API_KEY']
    provider.image = "Ubuntu 13.04 x64"
  end

  config.vm.define :server_name do |server_name|
    server_name.vm.hostname = ENV['HOSTNAME']
  end

end
